# Generated by Django 6.0.6 on 2026-07-02 11:49

import django.core.validators
import vehicles.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005 vehicleimage url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Preis muss größer als 0 sein.')], verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='leistung',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Leistung muss größer als 0 sein.'), django.core.validators.MaxValueValidator(2000, message='Leistung wirkt unrealistisch (max. 2000 PS).')], verbose_name='Leistung (PS)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Kilometerstand darf nicht negativ sein.'), django.core.validators.MaxValueValidator(1000000, message='Kilometerstand wirkt unrealistisch (max. 1.000.000 km).')], verbose_name='Kilometerstand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Preis muss größer als 0 sein.')], verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('reserved', 'Reserviert'), ('sold', 'Verkauft')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tueren',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Türanzahl muss mindestens 1 sein.'), django.core.validators.MaxValueValidator(8, message='Türanzahl wirkt unrealistisch (max. 8).')], verbose_name='Türanzahl'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(validators=[vehicles.models.validate_year], verbose_name='Baujahr'),
        ),
    ]