# Generated by Django 6.0.6 on 2026-07-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('vehicles', '0006_alter_pricehistory_price_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='admin_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('test_drive', 'Probefahrt'), ('consultation', 'Beratung'), ('delivery', 'Fahrzeugübergabe'), ('service', 'Werkstatt'), ('inquiry', 'Anfrage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Offen'), ('confirmed', 'Bestätigt'), ('rejected', 'Abgelehnt'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='pending', max_length=20),
        ),
    ]