# Generated by Django 6.0.6 on 2026-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]