# Generated by Django 6.0.6 on 2026-06-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_user'),
        ('documents', '0003_rename_created_at_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sale',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Kaufvertrag'), ('invoice', 'Rechnung'), ('id_card', 'Ausweis'), ('vehicle_doc', 'Fahrzeugdokument'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
